Update spec
getyourguide/partner-api-spec pull request #36
Opened 2022-10-13 15:29 UTC by stantalid

### Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

#### Screenshot (Optional)

New features / fixes can include a gif or screenshot of the functionality.

2022-10-14 10:46 UTC, maciekbb-gyg approved these changes

2022-11-07 14:28 UTC, OliverNikolai requested changes

2022-11-07 14:28 UTC, OliverNikolai commented on spec/paths/bookings.yaml
> -                - $ref: "../components/schema/bookings.yaml#/components/schemas/RedeemCoupon"
Why remove this?

2022-11-07 14:28 UTC, OliverNikolai commented on spec/paths/carts.yaml
> -                          - $ref: "../components/schema/carts.yaml#/components/schemas/CartsConfirmResponseInPayment"
This should also stay the same.

2022-11-07 14:28 UTC, OliverNikolai commented on spec/components/schema/payment.yaml
> +      enum: ["cc", "pp", "dd", "mb"]
Let's not expose this information. It will probably lead to partners who do not qualify for master bill to make many requests to care B2B teams.

2024-07-12 14:49 UTC, closed without merging